general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false
  # Whether to jump the cursor between windows focused by the WM.

  cursor_follow_focus: false
  # Whether to switch back and forth between the previously focused workspace

  # when focusing the current workspace.
  toggle_workspace_on_refocus: false
  # Whether to show floating windows as always on top.

  show_floating_on_top: false
  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)

  floating_window_move_amount: "5%"
  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable

  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  # window_animations: "unchanged"
  window_animations: "false"
gaps:
  # Gap between adjacent windows.
  inner_gap: "0px"
  # Gap between windows and the screen edge.

  outer_gap: "0px"
# Highlight active/inactive windows with a colored border.

# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#000066"
  inactive:
    enabled: false
    color: "#ff0000"
bar:
  height: "0px"
  position: "top"
  opacity: 0.6
  # background: "#20242cc4"

  background: "#00000000"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "10px"
  padding: "1px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
  components_right:
    #- type: "system tray"
    #- type: "tiling direction"
    #  label_horizontal: "⮂"
    #  label_vertical: "⮁"
    #  background: "#ffffff33"
    #  margin: "0 4px"
    #  padding: "0 8px"
    #- type: "binding mode"
    #  background: "#ffffff33"
    #  margin: "0 4px 0 0"
    #  padding: "0 8px"
    - type: "clock"
      # Documentation on formatting date/time string:

      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "HH:mm  ddd MMM d"
workspaces:
  - name: "1"
    keep_alive: true
  - name: "2"
    keep_alive: true
  - name: "3"
    keep_alive: true
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"
  - command: "ignore"
    match_process_name: "/heidisql.*/"
  - command: "ignore"
    match_process_name: "/SharpKeys|regedit/"
  - command: "set floating"
    # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).

    match_class_name: "#32770"
  - command: "resize borders 0px -7px -7px -7px"
    # Some applications (eg. Steam) have borders that extend past the normal border size.

    match_process_name: "steam"
binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      - command: "binding mode none"
        # Press enter/escape to return to default keybindings.

        bindings: ["Escape", "Enter"]
keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["F13+H", "F13+Left"]
  - command: "focus right"
    bindings: ["F13+L", "F13+Right"]
  - command: "focus up"
    bindings: ["F13+K", "F13+Up"]
  - command: "focus down"
    bindings: ["F13+J", "F13+Down"]
  - command: "move left"
    # Move focused window in a given direction.

    bindings: ["F13+Shift+H", "F13+Shift+Left"]
  - command: "move right"
    bindings: ["F13+Shift+L", "F13+Shift+Right"]
  - command: "move up"
    bindings: ["F13+Shift+K", "F13+Shift+Up"]
  - command: "move down"
    bindings: ["F13+Shift+J", "F13+Shift+Down"]
  - command: "resize width -2%"
    # Resize focused window by a percentage or pixel amount.

    binding: "F13+U"
  - command: "resize width +2%"
    binding: "F13+P"
  - command: "resize height +2%"
    binding: "F13+O"
  - command: "resize height -2%"
    binding: "F13+I"
  - command: "binding mode resize"
    # As an alternative to the resize keybindings above, resize mode enables resizing via

    # HJKL or arrow keys. The binding mode is defined above with the name "resize".
    binding: "F13+R"
  - command: "tiling direction toggle"
    # Change tiling direction. This determines where new tiling windows will be inserted.

    binding: "F13+V"
  - command: "focus mode toggle"
    # Change focus between floating / tiling windows.

    binding: "F13+Space"
  - command: "toggle floating"
    # Change the focused window to be floating / tiling.

    binding: "F13+Shift+Space"
  - command: "toggle maximized"
    # Change the focused window to be maximized / unmaximized.

    binding: "F13+X"
  - command: "set minimized"
    # Minimize focused window.

    binding: "F13+M"
  - command: "close"
    # Close focused window.

    binding: "F13+Shift+Q"
  - command: "exit wm"
    # Kill GlazeWM process safely.

    binding: "F13+Shift+E"
  - command: "reload config"
    # Re-evaluate configuration file.

    binding: "F13+Shift+R"
  - command: "exec wt"
    # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`

    # to start Windows Terminal and Git Bash respectively.
    binding: "F13+Enter"
  - command: "focus workspace recent"
    # Focus the workspace that last had focus.

    binding: "F13+Y"
  - command: "focus workspace next"
    # Focus the next/previous workspace defined in `workspaces` config.

    binding: "F13+T"
  - command: "focus workspace prev"
    binding: "F13+Shift+T"
  - command: "focus workspace 1"
    # Change focus to a workspace defined in `workspaces` config.

    binding: "F13+1"
  - command: "focus workspace 2"
    binding: "F13+2"
  - command: "focus workspace 3"
    binding: "F13+3"
  - command: "focus workspace 4"
    binding: "F13+4"
  - command: "focus workspace 5"
    binding: "F13+5"
  - command: "focus workspace 6"
    binding: "F13+6"
  - command: "focus workspace 7"
    binding: "F13+7"
  - command: "focus workspace 8"
    binding: "F13+8"
  - command: "focus workspace 9"
    binding: "F13+9"
  - command: "move workspace left"
    # Move focused workspace to a monitor in a given direction.

    binding: "F13+A"
  - command: "move workspace right"
    binding: "F13+F"
  - command: "move workspace up"
    binding: "F13+D"
  - command: "move workspace down"
    binding: "F13+S"
  - commands: ["move to workspace 1", "focus workspace 1"]
    # Move focused window to a workspace defined in `workspaces` config.

    binding: "F13+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "F13+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "F13+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "F13+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "F13+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "F13+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "F13+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "F13+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["F13+Shift+9"]
